baseURL: "https://jaredyam.github.io"
languageCode: "en-us"
defaultContentLanguage: zh
title: "ğŸ‘¨â€ğŸŒ¾ Jared Yam"
theme: PaperMod
enableGitInfo: true

menu:
  main:
    - identifier: Archive
      name: ğŸ“š Archive
      url: "/archives/"
      weight: 10
    - identifier: Tags
      name: ğŸ· Tags
      url: "/tags/"
      weight: 20
    - identifier: Search
      name: ğŸ” Search
      url: "/search/"
      weight: 30

# Search page
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

params:
  defaultTheme: light
  ShowToc: true
  TocOpen: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
  comments: true
  commentsParams:
    repo: "jaredyam/jaredyam.github.io"
    issueTerm: title
    label: Comment
  DateFormat: 2006 å¹´January 2 æ—¥

frontmatter:
  lastmod:
  - :git
  - lastmod
  - date