baseURL: https://jaredyam.github.io
languageCode: en-us
defaultContentLanguage: zh
title: ğŸ‘¨â€ğŸŒ¾ Jared Yam
theme: PaperMod
enableGitInfo: true
hasCJKLanguage: true
summaryLength: 90

menu:
  main:
    - identifier: Archive
      name: ğŸ“š Archive
      url: /archives/
      weight: 10
    - identifier: Tags
      name: ğŸ· Tags
      url: /tags/
      weight: 20
    - identifier: Search
      name: ğŸ” Search
      url: /search/
      weight: 30

# Search page
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

params:
  defaultTheme: light
  ShowToc: true
  TocOpen: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
  comments: true
  commentsParams:
    repo: jaredyam/jaredyam.github.io
    repoId: R_kgDOG9Gq_Q
    category: Announcements
    categoryId: DIC_kwDOG9Gq_c4CO_p0
    mapping: title
    reactionsEnabled: 1
    emitMetadata: 1
    inputPosition: top
    lang: zh-CN
  DateFormat: 2006 å¹´ 1 æœˆ 2 æ—¥
  autonumbering: true

frontmatter:
  lastmod:
  - :git
  - lastmod
  - date